echo ""
echo "============================================"
echo "  Setup complete! Starting the app..."
echo "============================================"
echo ""
echo "  Frontend  ->  http://localhost:5173"
echo "  Backend   ->  http://localhost:5000"
echo ""
echo "  Admin login:    admin@company.com    / admin123"
echo "  Employee login: employee@company.com / emp123"
echo ""
echo "  Press Ctrl+C to stop."
echo "
